name: Pull Request CI

on:
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# Checkout source code
    - uses: actions/checkout@v2
    
    - name: Checkout 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: gh pr checkout ${{ github.event.pull_request.number }}
  
# Cache maven stuff
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and test
      run: ./build/build.sh

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v1.0.0
      with:
        jacoco-csv-file: testreport/target/site/jacoco-aggregate/jacoco.csv

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: testreport/target/site/jacoco-aggregate/

    - name: Save PR number
      run: |
        mkdir -p ./pr
        echo ${{ github.event.number }} > ./pr/NR

    - uses: actions/upload-artifact@v2
      with:
        name: pr
        path: |
          pr/
          testreport/target/site/jacoco-aggregate/jacoco.csv
