name: Pull Request CI

on:
  pull_request: ~

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
# Checkout source code
    - uses: actions/checkout@v2
    
    - name: Checkout 
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
      run: gh pr checkout ${{ github.event.pull_request.number }}
  
# Cache maven stuff
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build and test
      run: ./build/build.sh

    - name: Generate Jacoco Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v1.0.0
      with:
        jacoco-csv-file: testreport/target/site/jacoco-aggregate/jacoco.csv

    - name: Log coverage percentage
      run: |
        echo "coverage = ${{ steps.jacoco.outputs.coverage }}"

    - name: Update coverage badge
      run: ./build/badge-update.sh

    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: testreport/target/site/jacoco-aggregate/

    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.number }}
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [create-or-update-comment][1]
          
          [1]: https://github.com/peter-evans/create-or-update-comment
        reactions: '+1'
